version: '3.4'

networks:
  frontend: 
  backend: 

services:
  productcatalog:
    image: jewels/catalog
    build:
      context: .\ProductCatalog
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=CatalogDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;"
      ExternalBaseUrl: http://localhost:7000
    ports:
      - "7000:80"
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend
    depends_on: 
      - mssqlserver

  tokenserver:
    image: jewels/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password=ProductApi123(!);Connect Timeout=30;TrustServerCertificate=false;Encrypt=false;"
      MvcClient: http://localhost:7500
    ports:
      - "7800:80"
    container_name: jewelstokenapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver

  cart:
    image: jewels/cartapi
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    environment:
      IdentityUrl: http://172.22.32.1:7800
      ConnectionString: basket.data
    ports:
      - "7010:80"
    container_name: jewelscartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basket.data

  jewelwebclient:
    image: jewels/jewelclient
    build: 
      context: .\JewelWebClient
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://productcatalog
      IdentityUrl: http://172.22.32.1:7800
      CallbackUrl: http://localhost:7500
    ports:
      - "7500:80"
    container_name: webshop
    networks: 
      - frontend
    depends_on:
      - productcatalog
      - tokensqlserver


  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
    ports:
      - "7002:1433"
    container_name: jewelscatalogserver
    networks:
      - backend


  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
    ports:
      - "1449:1433"
    container_name: jewelstokensqlserver
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "7050:6379"
    container_name: basketdata
    networks:
      - backend

